_wandb:
    value:
        cli_version: 0.23.1
        code_path: code/train_wan22_ti2v_motion_depth.py
        e:
            p5qhay8vsel2uw4j062m6ihaf5x2sqff:
                args:
                    - --dataset_base_path
                    - /nyx-storage1/hanliu/Sim_Physics/TestOutput
                    - --dataset_metadata_path
                    - /home/mzh1800/DiffSynth-Studio/data/sim_physics_metadata.csv
                    - --dataset_repeat
                    - "100"
                    - --height
                    - "480"
                    - --width
                    - "480"
                    - --num_frames
                    - "49"
                    - --model_paths
                    - '["/nyx-storage1/hanliu/world_model_ckpt/Wan-AI/Wan2.2-TI2V-5B", "/nyx-storage1/hanliu/world_model_ckpt/Wan-AI/Wan2.1-T2V-1.3B/models_t5_umt5-xxl-enc-bf16.pth", "/nyx-storage1/hanliu/world_model_ckpt/Wan-AI/Wan2.2-TI2V-5B/Wan2.2_VAE.pth"]'
                    - --output_path
                    - /nyx-storage1/hanliu/world_model_ckpt/Wan-AI/wan22_ti2v_stage1
                    - --training_mode
                    - heads_only
                    - --motion_loss_weight
                    - "1.0"
                    - --depth_loss_weight
                    - "1.0"
                    - --learning_rate
                    - "1e-4"
                    - --num_epochs
                    - "10"
                    - --batch_size
                    - "1"
                    - --gradient_accumulation_steps
                    - "8"
                    - --save_steps
                    - "500"
                    - --use_wandb
                    - --wandb_project
                    - wan22-ti2v-stage1-heads
                codePath: train_wan22_ti2v_motion_depth.py
                codePathLocal: train_wan22_ti2v_motion_depth.py
                cpu_count: 48
                cpu_count_logical: 48
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "52403109888"
                        used: "1523961856"
                email: swu@u.northwestern.edu
                executable: /nyx-storage1/hanliu/miniconda3/envs/diffsyn/bin/python3.10
                git:
                    commit: 06ff1fe25a233252a743ea2a1bb5e57f4e7b4c6e
                    remote: https://github.com/Windsao/Sim4VideoGen.git
                gpu: NVIDIA A40
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-d45a890a-299b-6fba-3e5b-a5d5865ae7ad
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-1a0e6066-3fe2-46e4-4fe2-978b6a7af90f
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-fd0797b1-b15c-fc40-f622-a0857bbe6759
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-74e3fbf0-1c36-f3a8-50b5-63b28f743339
                host: nyx.cs.northwestern.edu
                memory:
                    total: "404373401600"
                os: Linux-4.18.0-553.89.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /home/mzh1800/DiffSynth-Studio/train_wan22_ti2v_motion_depth.py
                python: CPython 3.10.18
                root: /home/mzh1800/DiffSynth-Studio
                startedAt: "2025-12-18T16:34:49.661564Z"
                writerId: p5qhay8vsel2uw4j062m6ihaf5x2sqff
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 98
            "3":
                - 16
            "4": 3.10.18
            "5": 0.23.1
            "6": 4.56.2
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 1
dataset_base_path:
    value: /nyx-storage1/hanliu/Sim_Physics/TestOutput
dataset_metadata_path:
    value: /home/mzh1800/DiffSynth-Studio/data/sim_physics_metadata.csv
dataset_repeat:
    value: 100
depth_head_checkpoint:
    value: null
depth_loss_weight:
    value: 1
gradient_accumulation_steps:
    value: 8
height:
    value: 480
learning_rate:
    value: 0.0001
lora_checkpoint:
    value: null
lora_rank:
    value: 32
lora_target_modules:
    value: q,k,v,o,ffn.0,ffn.2
model_id_with_origin_paths:
    value: null
model_paths:
    value: '["/nyx-storage1/hanliu/world_model_ckpt/Wan-AI/Wan2.2-TI2V-5B", "/nyx-storage1/hanliu/world_model_ckpt/Wan-AI/Wan2.1-T2V-1.3B/models_t5_umt5-xxl-enc-bf16.pth", "/nyx-storage1/hanliu/world_model_ckpt/Wan-AI/Wan2.2-TI2V-5B/Wan2.2_VAE.pth"]'
motion_head_checkpoint:
    value: null
motion_loss_weight:
    value: 1
num_epochs:
    value: 10
num_frames:
    value: 49
output_path:
    value: /nyx-storage1/hanliu/world_model_ckpt/Wan-AI/wan22_ti2v_stage1
save_steps:
    value: 500
spatiotemporal_depth_type:
    value: simple
training_mode:
    value: heads_only
use_spatiotemporal_depth:
    value: false
use_wandb:
    value: true
wandb_project:
    value: wan22-ti2v-stage1-heads
width:
    value: 480
